packages:
  - packages/**
  - plugins/**
  - services/**
  - examples/**
  - docs/**
  - apps/**
  - '!**/dist/**'

catalog:
  '@guiiai/logg': 1.1.0
  '@moeru/eslint-config': 0.1.0-beta.13
  '@moeru/std': 0.1.0-beta.13
  '@proj-airi/drizzle-duckdb-wasm': ^0.4.29
  '@xsai-ext/providers-cloud': ^0.4.0-beta.9
  '@xsai-ext/providers-local': ^0.4.0-beta.9
  '@xsai-ext/shared-providers': 0.4.0-beta.5
  '@xsai/embed': ^0.4.0-beta.9
  '@xsai/generate-speech': 0.4.0-beta.5
  '@xsai/generate-text': ^0.4.0-beta.9
  '@xsai/generate-transcription': ^0.4.0-beta.9
  '@xsai/model': ^0.4.0-beta.9
  '@xsai/shared': ^0.4.0-beta.9
  '@xsai/shared-chat': ^0.4.0-beta.9
  '@xsai/stream-text': ^0.4.0-beta.9
  '@xsai/tool': ^0.4.0-beta.9
  '@xsai/utils-chat': 0.4.0-beta.5
  xsschema: ^0.4.0-beta.9

catalogs:
  rolldown-vite:
    vite: npm:rolldown-vite@^7.2.5
